---
language: php

php:
  - '7.1'

cache:
  directories:
    - "node_modules"
    - "vendor"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database travis_database_test;'
  - composer self-update
  - composer install
  - npm install
  - npm install -g gulp-cli

script:
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - gulp
  - vendor/bin/phpunit